application: sample-app
version: 1
runtime: python27
api_version: 1

threadsafe: true

libraries:
- name: webapp2
  version: latest

builtins:
- remote_api: on

handlers:

- url: /incremental_fonts/?
  script: incremental_fonts.app
